// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqpN8CbMvUTvs0h3Eh75fWqwyflefgQI8',
    appId: '1:92958585203:android:20c70acfb670c8e5165506',
    messagingSenderId: '92958585203',
    projectId: 'my-project-1498938279301',
    databaseURL: 'https://my-project-1498938279301.firebaseio.com',
    storageBucket: 'my-project-1498938279301.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdZNekzzA7niwFiLsXJu-El8zWnb8oO4U',
    appId: '1:92958585203:ios:5bdf9d06911e28ce165506',
    messagingSenderId: '92958585203',
    projectId: 'my-project-1498938279301',
    databaseURL: 'https://my-project-1498938279301.firebaseio.com',
    storageBucket: 'my-project-1498938279301.appspot.com',
    iosClientId: '92958585203-q9mstn5183i3bkpahc7lu1b55reu5kun.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopapp',
  );
}
